language: csharp
mono: none
os: linux
dist: xenial
dotnet: 5.0.100

before_install:
  - export PATH=$PATH:$HOME/.dotnet/tools
  - dotnet tool install -g paket
  - dotnet tool restore

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.local/share/NuGet/Cache
    - $HOME/.nuget/packages

env:
  - FAKE_DETAILED_ERRORS=true

services:
  - docker

jobs:
  include:
    - stage: build
      if: tag =~ ^\d+\.\d+\.\d+-[a-zA-Z0-9.]+$
      script: dotnet fake build -t publish
      deploy:
        - provider: script
          cleanup: true
          script: dotnet fake build -t docker:publish -- -t $TRAVIS_TAG -n hkccr.ccs.tencentyun.com/zeeko/blog-server -l
          on:
            tags: true
