# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'

      - name: Setup
        run: |
          dotnet tool restore
          dotnet paket restore
          dotnet fake build -t github-actions

      - name: Build
        run: dotnet fake build -t publish

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{secrets.DOCKER_USERNAME}}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{secrets.DOCKER_PASSWORD}}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{secrets.DOCKER_REGISTRY}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          tags: ${{env.DOCKER_TAGS}}
          context: ${{github.workspace}}
          push: true
